---
title: "01 Intro to the tidyverse"
#author: "Bhavana Sirumalla"
#date: "2022-03"
output:
  html_document:
    toc: true
    toc_float: true
    df_print: paged
    collapsed: false
    number_sections: true
    toc_depth: 3
    #code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```

# Introduction to tidyverse

## Challenge

```{r}
# Data Science at TUHH ------------------------------------------------------
# SALES ANALYSIS ----
# 1.0 Load libraries ----
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(writexl)
# 2.0 Importing Files ----
bikes <- read_excel("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/00_data/bikes.xlsx")
orderLines <- read_excel("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/00_data/orderlines.xlsx")
bikeshops <- read_excel("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/00_data/bikeshops.xlsx")
# 3.0 Examining Data ----

# 4.0 Joining Data ----
bikeshop_orderlines_joined_tbl <- orderLines %>%
  left_join(bikes,by=c("product.id"="bike.id")) %>%
  left_join(bikeshops, by=c("customer.id"="bikeshop.id"))

# 5.0 Wrangling Data ----
bikeshop_orderlines_data <- bikeshop_orderlines_joined_tbl %>% 
  separate(col = location, into = c("City","State"), sep = ",") %>%
  mutate(total.price = price * quantity) %>%
  select(-...1, -gender) %>%
  select(-ends_with(".id")) %>%
  bind_cols(bikeshop_orderlines_joined_tbl %>% select(order.id)) %>%
  select(order.id, contains("order"), contains("model"), State,
         price, quantity, total.price,
         everything()) %>%
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))


# 6.0 Business Insights ----
# 6.1 Sales by Year ----
# 6.2 Sales by Year and Category 2 ----

sales_by_State_data= bikeshop_orderlines_data %>%
  select(State,total_price) %>%
  group_by(State)%>% summarise(sales=sum(total_price)) %>% mutate(sales_text = 
                                                                 scales::dollar
                                                               (sales, big.mark
                                                                 = ".",
                                                                 decimal.mark = 
                                                                   ",",
                                                                 prefix = "", 
                                                                 suffix = " €"))

sales_by_State_data%>%
  ggplot(aes(x = State, y = sales)) +
  geom_col(fill = "#2DC6D6") +
  geom_label(aes(label = sales_text),label.size = 0.01)+
  geom_smooth(method = "lm", se = FALSE) + 
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(title    = "Revenue by State", x = "",
       y = "Revenue") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))


# Step 1 - Manipulate
salesby_year_state <-  bikeshop_orderlines_data %>% 
  select(order_date,State,total_price) %>% mutate(yr=year(order_date)) %>% 
  group_by(yr,State) %>% summarise(sales= sum(total_price)) %>% mutate(
    sales_text = scales::dollar(sales, big.mark= ".",decimal.mark = ",",
                                prefix = "", suffix = " €"))


# Step 2 - Visualize
salesby_year_state %>%
  
  # Set up x, y, fill
  ggplot(aes(x = yr, y = sales, fill = State)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ State) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and State",
    fill = "Main category" # Changes the legend name
  ) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1,size = 7))

# 7.0 Writing Files ----

# 7.1 Excel ----
#install.packages("writexl")
library("writexl")

bikeshop_orderlines_data %>% write_xlsx("00_data/bike_orderlines.xlsx")
# 7.2 CSV ----
bikeshop_orderlines_data %>% write_csv("00_data/bike_orderlines.csv")
# 7.3 RDS ----
bikeshop_orderlines_data %>% write_rds("00_data/bike_orderlines.rds")
```
## Business case
```{r}
# Data Science at TUHH ------------------------------------------------------
# SALES ANALYSIS ----

# 1.0 Load libraries ----
library(tidyverse)
library(readxl)
# 2.0 Importing Files ----
# A good convention is to use the file name and suffix it with tbl for the data structure tibble
bikes_tbl      <- read_excel(path = "00_data/bikes.xlsx")
orderlines_tbl <- read_excel("00_data/orderlines.xlsx")

# Not necessary for this analysis, but for the sake of completeness
bikeshops_tbl  <- read_excel("00_data/bikeshops.xlsx")

# 3.0 Examining Data ----
orderlines_tbl
#glimpse(orderlines_tbl)

# 4.0 Joining Data ----

left_join(orderlines_tbl, bikes_tbl, by = c("product.id" = "bike.id"))
# Chaining commands with the pipe and assigning it to order_items_joined_tbl
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

# Examine the results with glimpse()
#bike_orderlines_joined_tbl %>% glimpse()

# 5.0 Wrangling Data ----
bike_orderlines_joined_tbl %>% 
  select(category) %>%
  filter(str_detect(category, "^Mountain")) %>% 
  unique()
# All actions are chained with the pipe already. You can perform each step separately and use glimpse() or View() to validate your code. Store the result in a variable at the end of the steps.
bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  # 5.1 Separate category name
  separate(col    = category,
           into   = c("category.1", "category.2", "category.3"),
           sep    = " - ") %>%
  
  # 5.2 Add the total price (price * quantity) 
  # Add a column to a tibble that uses a formula-style calculation of other columns
  mutate(total.price = price * quantity) %>%
  
  # 5.3 Optional: Reorganize. Using select to grab or remove unnecessary columns
  # 5.3.1 by exact column name
  select(-...1, -gender) %>%
  
  # 5.3.2 by a pattern
  # You can use the select_helpers to define patterns. 
  # Type ?ends_with and click on Select helpers in the documentation
  select(-ends_with(".id")) %>%
  
  # 5.3.3 Actually we need the column "order.id". Let's bind it back to the data
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  # 5.3.4 You can reorder the data by selecting the columns in your desired order.
  # You can use select_helpers like contains() or everything()
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  
  # 5.4 Rename columns because we actually wanted underscores instead of the dots
  # (one at the time vs. multiple at once)
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))
# 6.0 Business Insights ----
# 6.1 Sales by Year ----
library(lubridate)
# Step 1 - Manipulate
sales_by_year_tbl <- bike_orderlines_wrangled_tbl %>%
  
  # Select columns
  select(order_date, total_price) %>%
  
  # Add year column
  mutate(year = year(order_date)) %>%
  
  # Grouping by year and summarizing sales
  group_by(year) %>% 
  summarize(sales = sum(total_price)) %>%
  
  # Optional: Add a column that turns the numbers into a currency format 
  # (makes it in the plot optically more appealing)
  # mutate(sales_text = scales::dollar(sales)) <- Works for dollar values
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_year_tbl
# Step 2 - Visualize
sales_by_year_tbl %>%
  
  # Setup canvas with the columns year (x-axis) and sales (y-axis)
  ggplot(aes(x = year, y = sales)) +
  
  # Geometries
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label(aes(label = sales_text)) + # Adding labels to the bars
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  
  # Formatting
  # scale_y_continuous(labels = scales::dollar) + # Change the y-axis. 
  # Again, we have to adjust it for euro values
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by year",
    subtitle = "Upward Trend",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )

# 6.2 Sales by Year and Category 2 ----

# Step 1 - Manipulate
sales_by_year_cat_1_tbl <- bike_orderlines_wrangled_tbl %>%
  
  # Select columns and add a year
  select(order_date, total_price, category_1) %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and main catgegory
  group_by(year, category_1) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

sales_by_year_cat_1_tbl  
# Step 2 - Visualize
sales_by_year_cat_1_tbl %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = category_1)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ category_1) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and main category",
    subtitle = "Each product category has an upward trend",
    fill = "Main category" # Changes the legend name
  )


# 7.0 Writing Files ----

# 7.1 Excel ----
#install.packages("writexl")
library("writexl")
bike_orderlines_wrangled_tbl %>%
  write_xlsx("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/tidyverse/01_bike_sales/02_wrangled_data/bike_orderlines.xlsx")
#C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/tidyverse/01_bike_sales/02_wrangled_data/bike_orderlines.xlsx
# 7.2 CSV ----
bike_orderlines_wrangled_tbl %>% 
  write_csv("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/tidyverse/01_bike_sales/02_wrangled_data/bike_orderlines.csv")

# 7.3 RDS ----
bike_orderlines_wrangled_tbl %>% 
  write_rds("C:/Bhavana/LECTURES/Sem 3/ds_basics-BhavanaSirumalla/tidyverse/01_bike_sales/02_wrangled_data/bike_orderlines.rds")

```